knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(default:/usr/bin/wkhtmltopdf:WKHTMLTOPDF_PATH)%'
        options:
            - { name: 'viewport-size', value: '1024x768' }
            - { name: 'page-size', value: 'A4'}
    image:
        enabled:    true
        binary:     '%env(default:/usr/bin/wkhtmltoimage:WKHTMLTOIMAGE_PATH)%'
        options:    []
